# Generated by Django 5.0.6 on 2024-06-05 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clearance_documents/')),
                ('description', models.TextField()),
                ('document_type', models.CharField(choices=[('course_form_100l_alpha', 'Course Form (100L Alpha Semester)'), ('course_form_100l_omega', 'Course Form (100L Omega Semester)'), ('course_form_200l_alpha', 'Course Form (200L Alpha Semester)'), ('course_form_200l_omega', 'Course Form (200L Omega Semester)'), ('course_form_300l_alpha', 'Course Form (300L Alpha Semester)'), ('course_form_300l_omega', 'Course Form (300L Omega Semester)'), ('course_form_400l_alpha', 'Course Form (400L Alpha Semester)'), ('course_form_400l_omega', 'Course Form (400L Omega Semester)'), ('bio_data', 'Bio-data'), ('local_government_certificate', 'Local Government Certificate'), ('birth_certificate', 'Birth Certificate'), ('jamb_admission_letter', 'Jamb Admission Letter'), ('du_admission_letter', 'DU Admission Letter'), ('letter_of_undertaking', 'Letter of Undertaking'), ('others', 'Others')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('matric_number', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='pending', max_length=255)),
                ('name', models.CharField(choices=[('computing_and_applied_sciences', 'Computing and Applied Sciences'), ('arts_and_management_sciences', 'Arts and Management Sciences')], max_length=255, unique=True)),
                ('documents', models.ManyToManyField(blank=True, to='MySite.clearancedocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='pending', max_length=255)),
                ('name', models.CharField(choices=[('computer_science', 'Computer Science'), ('software_engineering', 'Software Engineering'), ('cyber_security', 'Cyber Security'), ('microbiology', 'Microbiology'), ('biochemistry', 'Biochemistry'), ('industrial_chemistry', 'Industrial Chemistry'), ('economics', 'Economics'), ('accounting', 'Accounting'), ('business_administration', 'Business Administration'), ('mass_communication', 'Mass Communication'), ('criminology', 'Criminology')], max_length=255, unique=True)),
                ('documents', models.ManyToManyField(blank=True, to='MySite.clearancedocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='pending', max_length=255)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('documents', models.ManyToManyField(blank=True, to='MySite.clearancedocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClearanceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('alpha', 'Alpha'), ('omega', 'Omega')], max_length=255)),
                ('session', models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030')], default='2023/2024', max_length=11)),
                ('bursary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursary_clearance_requests', to='MySite.bursary')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_clearance_requests', to='MySite.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_clearance_requests', to='MySite.faculty')),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_clearance_requests', to='MySite.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.student')),
            ],
        ),
    ]
