# Generated by Django 5.0.6 on 2024-06-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='hostel',
            name='documents',
            field=models.ManyToManyField(blank=True, to='MySite.clearancedocument'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='hostel',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySite.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(choices=[('computing_and_applied_sciences', 'Computing and Applied Sciences'), ('arts_and_management_sciences', 'Arts and Management Sciences')], max_length=255, unique=True),
        ),
    ]
