# Generated by Django 5.0.6 on 2024-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_remove_student_middle_name_hostel_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='semester',
            field=models.CharField(choices=[('alpha', 'Alpha'), ('omega', 'Omega')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bursary',
            name='session',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030')], default='2023/2024', max_length=11),
        ),
        migrations.AddField(
            model_name='department',
            name='semester',
            field=models.CharField(choices=[('alpha', 'Alpha'), ('omega', 'Omega')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='session',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030')], default='2023/2024', max_length=11),
        ),
        migrations.AddField(
            model_name='faculty',
            name='semester',
            field=models.CharField(choices=[('alpha', 'Alpha'), ('omega', 'Omega')], default='alpha', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='session',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030')], default='2023/2024', max_length=11),
        ),
        migrations.AddField(
            model_name='hostel',
            name='semester',
            field=models.CharField(choices=[('alpha', 'Alpha'), ('omega', 'Omega')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='session',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030')], default='2023/2024', max_length=11),
        ),
    ]
